service: aws-node-rest

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
